apiVersion: v1
kind: Service
metadata:
  name: {{ include "remote-wake-sleep-on-lan.fullname" . }}
  labels:
    {{- include "remote-wake-sleep-on-lan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "remote-wake-sleep-on-lan.selectorLabels" . | nindent 4 }}
